# Site settings
author: Chen
title: Journey through Flatiron School
header-img: img/home-bg.png
email: yiliangchen0113@hotmail.com
copyright_name: Chen
description: > # this means to ignore newlines until "baseurl:"
  Killing my procrastination 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ychen0113

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
